/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('profile').del()
  await knex('profile').insert([
    //List of profiles to add
    { profileID: 1, 
      userID: 1,
      name: 'John Doe',
      interests: 'Blockchain',
      history: 'Process Engineer at Exxon',
      expertise: 'Computer Science',
      affiliation: 'Google',
    },
    { profileID: 2, 
      userID: 2,
      name: 'Jane Smith',
      interests: 'Sustainable Architecture',
      history: 'Researcher at Tesla',
      expertise: 'Mechanical Engineering',
      affiliation: 'Stanford University',
    },
    { profileID: 3, 
      userID: 3,
      name: 'Mike Brown',
      interests: 'Virtual Reality', 
      history: 'Art Director at MoMA',
      expertise: 'Fine Arts',
      affiliation: 'None',
    },
    { profileID: 4, 
      userID: 4,
      name: 'Emma Jones',
      interests: 'Robotics',
      history: 'Software Engineer at Microsoft',
      expertise: 'Computer Science',
      affiliation: 'OpenAI',
    },    
    { profileID: 5,   
      userID: 5,
      name: 'Samuel Green',
      interests: 'Carbon Capture',
      history: 'Environmental Consultant at BP',
      expertise: 'Environmental Science',
      affiliation: 'Greenpeace',  
    },
    { profileID: 6, 
      userID: 6,
      name: 'Olivia Adams',
      interests: 'Contemporary Sculpture',
      history: 'Gallery Curator at Tate Modern',  
      expertise: 'Art History',
      affiliation: 'None',
    },
    { profileID: 7, 
      userID: 7,
      name: 'Noah Wilson',  
      interests: 'Cybersecurity',
      history: 'Data Analyst at Meta',
      expertise: 'Data Science',
      affiliation: 'MIT',
    },  
    { profileID: 8, 
      userID: 8,
      name: 'Sophia Lee',
      interests: 'Solar Power',
      history: 'Renewable Energy Specialist at SunPower',
      expertise: 'Renewable Energy',  
      affiliation: 'Clean Energy Alliance',
    },
    { profileID: 9, 
      userID: 9,
      name: 'Liam Martin',
      interests: 'Quantum Computing',
      history: 'Machine Learning Engineer at Amazon',
      expertise: 'Artificial Intelligence',
      affiliation: 'None',
    },
    { profileID: 10, 
      userID: 10,
      name: 'Ava Thomas',
      interests: 'Film Production',
      history: 'Art Teacher at NYU',
      expertise: 'Visual Arts',
      affiliation: 'Guggenheim Foundation',
    },
    { profileID: 11, 
      userID: 11,
      name: 'Dr. Samuel Carter',
      interests: 'Renewable Energy, Sustainable Engineering',
      history: 'Professor of Environmental Engineering at MIT',
      expertise: 'Sustainable Energy Systems',
      affiliation: 'Massachusetts Institute of Technology',
    },
    { profileID: 12, 
      userID: 12,
      name: 'Prof. Elaine Zhang',
      interests: 'Artificial Intelligence, Ethics in Technology',
      history: 'Associate Professor of Computer Science at Stanford',
      expertise: 'AI and Machine Learning',
      affiliation: 'Stanford University',
    },
    { profileID: 13, 
      userID: 13,
      name: 'Dr. Marcus Bell',
      interests: 'Cybersecurity, Network Security',
      history: 'Lecturer at University of Texas at Austin',
      expertise: 'Cybersecurity and Cryptography',
      affiliation: 'University of Texas at Austin',
    },
    { profileID: 14, 
      userID: 14,
      name: 'Prof. Linda Vasquez',
      interests: 'Space Exploration, Aerospace Design',
      history: 'Professor of Aerospace Engineering at Caltech',
      expertise: 'Rocket Propulsion and Space Systems',
      affiliation: 'California Institute of Technology',
    },
    { profileID: 15, 
      userID: 15,
      name: 'Dr. Nathan Foster',
      interests: 'Psychology of Learning, Cognitive Science',
      history: 'Assistant Professor at Harvard University',
      expertise: 'Cognitive Neuroscience and Learning Theory',
      affiliation: 'Harvard University',
    },
    { profileID: 16, 
      userID: 16,
      name: 'Prof. Isabella Moreno',
      interests: 'Urban Development, Sustainable Cities',
      history: 'Professor of Urban Planning at Columbia University',
      expertise: 'Smart Cities and Infrastructure',
      affiliation: 'Columbia University',
    },
    { profileID: 17, 
      userID: 17,
      name: 'Dr. James Patel',
      interests: 'Biomedical Engineering, Medical Devices',
      history: 'Research Professor at Johns Hopkins University',
      expertise: 'Biomechanics and Medical Innovations',
      affiliation: 'Johns Hopkins University',
    },
    { profileID: 18, 
      userID: 18,
      name: 'Prof. Rebecca Owens',
      interests: 'Modern Architecture, Sustainable Design',
      history: 'Lecturer at University of California, Berkeley',
      expertise: 'Architectural Sustainability',
      affiliation: 'UC Berkeley',
    },
    { profileID: 19, 
      userID: 19,
      name: 'Dr. Henry Whitmore',
      interests: 'Data Science, Statistical Modeling',
      history: 'Senior Lecturer at Carnegie Mellon University',
      expertise: 'Big Data Analytics and Machine Learning',
      affiliation: 'Carnegie Mellon University',
    },
    { profileID: 20, 
      userID: 20,
      name: 'Prof. Olivia Bennett',
      interests: 'Human-Computer Interaction, UX Design',
      history: 'Professor of Informatics at University of Washington',
      expertise: 'HCI and User Experience Design',
      affiliation: 'University of Washington',
    },
  ]);
};

//Template for adding profiles
// { profileID: int, 
//   userID: int,
//   name: string,
//   interests: string,
//   history: string,
//   expertise: string,
//   affiliation: string,
// }