/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('events').del()
  await knex('events').insert([
    //List of events to add
    { eventID: 1, 
      instructorID: 1,
      topic: 'Blockchain',
      description: 'Blockchain is a new technology that is changing the world',
      date: '2025-09-14',
      field: 'Computer Science',
      course: 'Database Systems',
      affiliation: 'MIT',
      deliveryMethod: 'Online',
      status: 'Scheduled',
      requesterID: 7,
    },
    { eventID: 2, 
      instructorID: null,
      topic: 'Sustainable Architecture',
      description: 'Sustainable architecture focuses on designing and constructing buildings that minimize environmental impact, enhance energy efficiency, and promote long-term resilience through innovative materials and eco-friendly practices.',
      date: '2025-07-06',
      field: 'Architecture',
      course: 'Urban Planning',
      affiliation: 'Stanford University',
      deliveryMethod: 'In-Person',
      status: 'Pending',
      requesterID: 2,
    },
    { eventID: 3, 
      instructorID: 12,
      topic: 'Ethics in Artificial Intelligence',
      description: 'A discussion on the ethical implications of AI, including bias, accountability, and the future of machine learning in society.',
      date: '2025-08-21',
      field: 'Computer Science',
      course: 'Artificial Intelligence',
      affiliation: 'University of Texas at Austin',
      deliveryMethod: 'Online',
      status: 'Scheduled',
      requesterID: 13,
    },
    { eventID: 4, 
      instructorID: 13,
      topic: 'Cybersecurity in the Modern Age',
      description: 'Exploring the latest developments in cybersecurity, threat detection, and digital privacy.',
      date: '2025-10-05',
      field: 'Computer Science',
      course: 'Computer Networks',
      affiliation: 'Stanford University',
      deliveryMethod: 'In-Person',
      status: 'Scheduled',
      requesterID: 12,
    },
    { eventID: 5, 
      instructorID: 15,
      topic: 'Cognitive Science and Learning Theories',
      description: 'An in-depth seminar on how cognitive neuroscience can inform modern educational strategies.',
      date: '2025-06-15',
      field: 'Psychology',
      course: 'Psychology',
      affiliation: 'Johns Hopkins University',
      deliveryMethod: 'Online',
      status: 'Scheduled',
      requesterID: 17,
    },
    { eventID: 6, 
      instructorID: 14,
      topic: 'Advancements in Space Propulsion',
      description: 'A technical session covering innovations in rocket propulsion and their impact on space exploration.',
      date: '2025-09-30',
      field: 'Aerospace Engineering',
      course: 'Spacecraft Design',
      affiliation: 'Columbia University',
      deliveryMethod: 'In-Person',
      status: 'Scheduled',
      requesterID: 16,
    },
    { eventID: 7, 
      instructorID: 17,
      topic: 'Medical Innovations in Biomedical Engineering',
      description: 'A discussion on cutting-edge medical devices and how they are transforming healthcare.',
      date: '2025-07-25',
      field: 'Biomedical Engineering',
      course: 'Medical Imaging',
      affiliation: 'Harvard University',
      deliveryMethod: 'Online',
      status: 'Scheduled',
      requesterID: 15,
    },
    { eventID: 8, 
      instructorID: 2,
      topic: 'The Future of Smart Cities',
      description: 'How urban planning is evolving to incorporate smart infrastructure and sustainable design.',
      date: '2025-08-10',
      affiliation: 'California Institute of Technology',
      field: 'Architecture',
      course: 'Urban Planning',
      deliveryMethod: 'In-Person',
      status: 'Scheduled',
      requesterID: 14,
    },
    { eventID: 9, 
      instructorID: 7,
      topic: 'Big Data Analytics in Research',
      description: 'A workshop on utilizing big data techniques to gain insights in various fields of study.',
      date: '2025-09-12',
      field: 'Data Science',
      course: 'Big Data Analytics',
      affiliation: 'University of Washington',
      deliveryMethod: 'Online',
      status: 'Scheduled',
      requesterID: 20,
    },
    { eventID: 10, 
      instructorID: 5,
      topic: 'Sustainable Building Materials',
      description: 'Examining the latest trends in eco-friendly materials and sustainable construction techniques.',
      date: '2025-11-04',
      field: 'Architecture',
      course: 'Urban Planning',
      affiliation: 'Carnegie Mellon University',
      deliveryMethod: 'In-Person',
      status: 'Scheduled',
      requesterID: 19,
    },
    { eventID: 11, 
      instructorID: 20,
      topic: 'User Experience and Human-Computer Interaction',
      description: 'How UX design principles influence the development of user-friendly digital products.',
      date: '2025-06-20',
      field: 'Computer Science',
      course: 'Computer Architecture',
      deliveryMethod: 'Online',
      status: 'Scheduled',
      requesterID: 18,
    },
    { eventID: 12, 
      instructorID: null, //Could be user 5 or 8; good for searching
      topic: 'Introduction to Renewable Energy',
      description: 'An overview of sustainable energy technologies, including solar, wind, and hydroelectric power.',
      date: '2025-08-29',
      field: 'Environmental Engineering',
      course: 'Environmental Chemistry',
      affiliation: 'Massachusetts Institute of Technology',
      deliveryMethod: 'Online',
      status: 'Pending',
      requesterID: 11,
    },
  ]);
};
