/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('interests').del()
  await knex('interests').insert([
    //List of interests to add
    {userID: 1,
      'Computer Science': true,
      'Mathematics': true,
      'Physics': true,
      'Data Science': true,
    },
    {userID: 2,
      'Architecture': true,
      'Art': true,
      'Biology': true,
      'Environmental Engineering': true,
    },
    {userID: 3,
      'Computer Science': true,
      'Mathematics': true,
      'Art': true,
    },
    {userID: 4,
      'Computer Science': true,
      'Mathematics': true,
      'Data Science': true,
    },
    { userID: 5,
      'Environmental Engineering': true,
      'Biology': true,
    },
    { userID: 6,
      'Art': true,
    },
    { userID: 7,
      'Data Science': true,
      'Computer Science': true,
    },
    { userID: 8,
      'Environmental Engineering': true,
      'Chemistry': true,
    },
    { userID: 9,
      'Computer Science': true,
      'Mathematics': true,
      'Physics': true,
      'Data Science': true,
    },
    { userID: 10,
      'Art': true,
    },
    { userID: 11,
      'Environmental Engineering': true,
      'Chemistry': true,
      'Biology': true,
    },
    { userID: 12,
      'Computer Science': true,
      'Data Science': true,
    },
    { userID: 13,
      'Computer Science': true,
      'Data Science': true,
    },
    { userID: 14,
      'Aerospace Engineering': true,
      'Physics': true,
    },
    { userID: 15,
      'Psychology': true,
      'Biology': true,
    },
    { userID: 16,
      'Architecture': true,
      'Environmental Engineering': true,
    },
    { userID: 17,
      'Biomedical Engineering': true,
      'Biology': true,
      'Chemistry': true,
    },
    { userID: 18,
      'Architecture': true,
      'Environmental Engineering': true,
    },
    { userID: 19,
      'Data Science': true,
      'Mathematics': true,
      'Computer Science': true,
    },
    { userID: 20,
      'Computer Science': true,
      'Data Science': true,
    },
  ]);
};
