/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // // Deletes ALL existing entries
  // await knex('profiles').del()
  await knex('users').del()
  await knex('users').insert([
    //List of users to add
    { userID: 1, 
      email: 'john.doe@gmail.com',
      password: 'password123',
    },
    { userID: 2, 
      email: 'jane.smith@yahoo.com',
      password: 'qwerty2023',
    },
    { userID: 3, 
      email: 'mike.brown@outlook.com',
      password: 'mikepass789',
    },
    { userID: 4, 
      email: 'emma.jones@gmail.com',
      password: 'Emma!2023',
    },
    { userID: 5, 
      email: 'samuel.green@icloud.com',
      password: 'sgreen_456',
    },
    { userID: 6, 
      email: 'olivia.adams@gmail.com',
      password: 'Liv$ecure',
    },
    { userID: 7, 
      email: 'noah.wilson@aol.com',
      password: 'Wilson_789',
    },
    { userID: 8, 
      email: 'sophia.lee@gmail.com',
      password: 'Sophia#2024',
    },
    { userID: 9, 
      email: 'liam.martin@hotmail.com',
      password: 'martin_321',
    },
    { userID: 10, 
      email: 'ava.thomas@gmail.com',
      password: 'Ava!789pass',
    },
    { userID: 11, 
      email: 'samuel.carter@mit.edu',
      password: 'SamCarterGreen123!',
    },
    { userID: 12, 
      email: 'elaine.zhang@stanford.edu',
      password: 'ElaineAI456#',
    },
    { userID: 13, 
      email: 'marcus.bell@utexas.edu',
      password: 'MarcusCyber789%',
    },
    { userID: 14, 
      email: 'linda.vasquez@caltech.edu',
      password: 'LindaRocket321@',
    },
    { userID: 15, 
      email: 'nathan.foster@harvard.edu',
      password: 'NathanNeuro999$',
    },
    { userID: 16, 
      email: 'isabella.moreno@columbia.edu',
      password: 'IsabellaUrban777&',
    },
    { userID: 17, 
      email: 'james.patel@jhu.edu',
      password: 'JamesMedTech2025*',
    },
    { userID: 18, 
      email: 'rebecca.owens@berkeley.edu',
      password: 'RebeccaArch888!',
    },
    { userID: 19, 
      email: 'henry.whitmore@cmu.edu',
      password: 'HenryBigData555@',
    },
    { userID: 20, 
      email: 'olivia.bennett@washington.edu',
      password: 'OliviaUX101#',
    },
  ]);
};

//Template for adding users
// { userID: int, 
//   email: string,
//   password: string,
// }

